# docker-compose.yml
#docker compose fileeeeeeeeeeeeeeeeeeeeeeee
version: '3.8'
services:
  nodejs-backend:    # Backend service
    container_name: nodejs-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://admin:iZ60gehGkw7Qy48T@mongodb-service:27017
      - JWT_SECRET=my_secret_string
      - CLIENT_URL=http://0.0.0.0:8080
      - BASE_API_URL=api
      - NODE_ENV=production
    depends_on:
      - mongodb-service
    networks:
      - cosc2767-network
    restart: unless-stopped

  mongodb-service:   # MongoDB service
    container_name: mongodb-service
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=iZ60gehGkw7Qy48T
    volumes:
      - mongodb_data:/data/db
    networks:
      - cosc2767-network
    restart: unless-stopped

networks:
  cosc2767-network:
    driver: bridge

volumes:
  mongodb_data:
